[project]
name = "gpt-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy==1.22",
    "tiktoken>=0.8.0",
    "torch==2.2.2",
    "transformers>=4.48.0",
]
